- src/mp_api/matproj.py
- src/mp_api/phonon/resources.py
- src/mp_api/search/query_operators.py
- src/mp_api/search/resources.py
- Added a custom thermo energy query operator for the search endpoint to allow for top level searching of energy data.
- Materials client returns individual documents in each chunk requested instead of full chunk
- Additional routes added to mass MPRester class
> Search endpoint bug fix, and client updates

- src/mp_api/matproj.py
- src/mp_api/search/client.py
- src/mp_api/search/query_operators.py
- src/mp_api/search/resources.py
- src/mp_api/thermo/query_operators.py
- Fix to `is_stable` query operator
- Added ability to query search endpoint using multiple task_ids
> Multiple task_id query added to search

- src/mp_api/core/client.py
- src/mp_api/core/resource.py
This PR fixes a bug with querying data from versioned endpoints. The default database version is pulled for every query to avoid incorrect collection naming.
> Version query bug fix

- src/mp_api/electrodes/models.py
updated the fields so that the document is in line with electrode document from this emmet PR
https://github.com/materialsproject/emmet/pull/178
> added more fields to electrode doc

- app.py
- src/mp_api/bandstructure/models/doc.py
- src/mp_api/core/api.py
- src/mp_api/core/query_operator.py
- src/mp_api/core/resource.py
- src/mp_api/dielectric/client.py
- src/mp_api/dielectric/query_operators.py
- src/mp_api/dois/client.py
- src/mp_api/elasticity/client.py
- src/mp_api/electrodes/query_operators.py
- src/mp_api/eos/client.py
- src/mp_api/eos/query_operators.py
- src/mp_api/fermi/client.py
- src/mp_api/gb/client.py
- src/mp_api/gb/query_operators.py
- src/mp_api/magnetism/query_operators.py
- src/mp_api/materials/query_operators.py
- src/mp_api/molecules/query_operators.py
- src/mp_api/mpcomplete/query_operator.py
- src/mp_api/phonon/client.py
- src/mp_api/piezo/query_operators.py
- src/mp_api/search/query_operators.py
- src/mp_api/substrates/query_operators.py
- src/mp_api/surface_properties/query_operators.py
- src/mp_api/synthesis/query_operators.py
- src/mp_api/tasks/client.py
- src/mp_api/thermo/models.py
- src/mp_api/thermo/query_operators.py
- src/mp_api/xas/query_operator.py
This PR  contains:
- `ensure_indexes` method added to query operator to define keys for MongoDB indexes
- Index setup method added to `Resource`
- Main app now checks for `API_DEBUG` environment variable to control whether the index setup methods for each resource are called
> MongoDB index management with API

- src/mp_api/core/api.py
Added CORS middleware to allow requests between a local web instance and the api.
@tschaume does keeping `allow_origins=["*"]` pose any major risks?
> Add CORS to enable resource sharing with local web instance

- requirements.txt
- setup.py
- src/mp_api/core/client.py
- src/mp_api/core/ratelimit.py
- src/mp_api/core/settings.py
Rate limiting added to core client query and post methods.
> Rate limiting added to core client

- src/mp_api/routes/synthesis/query_operators.py
- tests/synthesis/test_query_operators.py
This PR fixes the bug mentioned in issue #309 with `total_doc` population when filters are included in addition to keywords.
> Fix total_doc synth population

- requirements.txt
- src/mp_api/routes/charge_density/resources.py
- src/mp_api/routes/electrodes/resources.py
- src/mp_api/routes/electronic_structure/resources.py
This PR enabled direct responses encoded with MontyEncoder for large object endpoints.
> Enable direct response on appropriate endpoints

- requirements-server.txt
- requirements.txt
- setup.py
- src/mp_api/core/ratelimit.py
- src/mp_api/routes/charge_density/resources.py
- src/mp_api/routes/dielectric/resources.py
- src/mp_api/routes/dois/resources.py
- src/mp_api/routes/elasticity/resources.py
- src/mp_api/routes/electrodes/resources.py
- src/mp_api/routes/electronic_structure/resources.py
- src/mp_api/routes/eos/resources.py
- src/mp_api/routes/fermi/resources.py
- src/mp_api/routes/grain_boundary/resources.py
- src/mp_api/routes/magnetism/resources.py
- src/mp_api/routes/materials/resources.py
- src/mp_api/routes/molecules/resources.py
- src/mp_api/routes/oxidation_states/resources.py
- src/mp_api/routes/phonon/resources.py
- src/mp_api/routes/piezo/resources.py
- src/mp_api/routes/search/resources.py
- src/mp_api/routes/similarity/resources.py
- src/mp_api/routes/substrates/resources.py
- src/mp_api/routes/surface_properties/resources.py
- src/mp_api/routes/thermo/resources.py
- src/mp_api/routes/wulff/resources.py
- src/mp_api/routes/xas/resources.py
- tests/elasticity/test_client.py
> Orjson and rate limiting changes

- app.py
- src/mp_api/matproj.py
- src/mp_api/routes/__init__.py
- src/mp_api/routes/provenance/client.py
- src/mp_api/routes/provenance/client.pyi
- src/mp_api/routes/provenance/resources.py
- src/mp_api/routes/xas/client.py
- tests/test_client.py
- tests/test_mprester.py
> Provenance endpoint and test bug fixes

- tests/xas/test_query_operators.py
This fixes xas tests to accommodate change in query operators from `task_id` to `material_id`.
> Task_id to material_id in xas tests

- requirements.txt
- src/mp_api/client.py
- tests/test_mprester.py
- Add `get_pourbaix_entries` to MPRester with an equivalent call signature to the legacy pymatgen method
- Add support for calculating solid free energies via `GibbsComputedStructureEntry`
- Update the source of ion data to point to the MPContribs project
- Add `get_ion_reference_data` and `get_ion_entries` methods to make it a little easier and more transparent for users to customize Pourbaix diagrams
- Port legacy tests from pymatgen
- Add more tests
-  see above
- Various technical cleanups. See TODO comments throughout the code
- Make tests of `get_pourbaix_entries` more thorough
> Add Pourbaix client

- requirements.txt
- src/mp_api/client.py
- src/mp_api/routes/summary/client.py
- tests/test_mprester.py
This PR accommodates data changes involving the use of a new `HasProps` enum to define the `has_props` fields.
> Convert to using HasProps enum for summary client

- src/mp_api/client.py
- src/mp_api/core/client.py
Cleanups for #428 to enable caching
> Enable caching for get_ion_reference_data

- requirements-server.txt
- requirements.txt
- setup.py
- src/mp_api/client.py
- src/mp_api/routes/materials/hint_scheme.py
- src/mp_api/routes/materials/resources.py
- src/mp_api/routes/summary/hint_scheme.py
- src/mp_api/routes/summary/resources.py
- src/mp_api/routes/thermo/client.py
- tests/bonds/test_client.py
- tests/dielectric/test_client.py
- tests/magnetism/test_client.py
- tests/materials/test_hint_scheme.py
- tests/piezo/test_client.py
- tests/summary/test_hint_scheme.py
- tests/synthesis/test_client.py
- tests/test_mprester.py
- tests/thermo/test_client.py
This PR adds hints to the `materials` and `summary` endpoints using the new `HintScheme` class in Maggma.
> Hint schemes added to `materials` and `summary`

- src/mp_api/routes/materials/hint_scheme.py
- src/mp_api/routes/summary/hint_scheme.py
Patch hint schemes to default to returning an empty dictionary for the store argument.
> Patch hint schemes

- src/mp_api/__init__.py
- src/mp_api/core/client.py
- src/mp_api/routes/robocrys.py
- src/mp_api/routes/synthesis.py
- tests/test_mprester.py
This PR expands the use of threadpools for parallel requests. It also fixes some pagination bugs with some user requested values of `num_chunks` and `chunk_size`.
> Enhance parallel requests and bug fixes

- src/mp_api/client.py
Addresses issue described here: https://matsci.org/t/issue-querying-pourbaix-entries-using-the-mp-api-rester/40651/6
And also closes bug report action item for Fe-C Pourbaix diagram on web app.
> Use reference solids to construct the ion reference phase diagram

- src/mp_api/client.py
Checks that the API key is not 16 characters, meaning it would be a legacy API key.
> Add minimal API key validation

- .github/workflows/testing.yml
- src/mp_api/core/client.py
- src/mp_api/core/settings.py
- src/mp_api/routes/bonds.py
- src/mp_api/routes/dielectric.py
- src/mp_api/routes/elasticity.py
- src/mp_api/routes/electrodes.py
- src/mp_api/routes/electronic_structure.py
- src/mp_api/routes/eos.py
- src/mp_api/routes/grain_boundary.py
- src/mp_api/routes/magnetism.py
- src/mp_api/routes/materials.py
- src/mp_api/routes/molecules.py
- src/mp_api/routes/piezo.py
- src/mp_api/routes/robocrys.py
- src/mp_api/routes/substrates.py
- src/mp_api/routes/summary.py
- src/mp_api/routes/surface_properties.py
- src/mp_api/routes/synthesis.py
- src/mp_api/routes/thermo.py
- src/mp_api/routes/xas.py
- tests/test_client.py
- tests/test_core_client.py
This PR updates pagination, sorting, and fields projection query parameters which are changed in https://github.com/materialsproject/maggma/pull/620
It also renamed `chunk` and `num_chunks` to `page` and `per_page` to be commensurate with maggma pagination changes.
> Update prefixed query params

- src/mp_api/client.py
This PR implements a check for the AWS_EXECUTION_ENV environment variable to determine whether to ping the MinIO or AWS S3 bucket object URLs for charge density data.
> Check for AWS deployment in CHGCAR lookup

- src/mp_api/client.py
Increase the number of seconds before a timeout error is thrown when retrieving charge densities.
> Change s3 timeout values

- src/mp_api/client.py
- src/mp_api/routes/charge_density.py
- tests/test_charge_density.py
This PR switches out direct GET requests to S3 object URLs for use of boto3.
> Use boto3 instead of direct get requests in client for charge density data

- src/mp_api/routes/charge_density.py
Fixes a bug where the bucket name was not being retrieved when the API client is used within an AWS deployment.
> Ensure bucket name is present for AWS deployment

- src/mp_api/routes/charge_density.py
Make sure the boto session is not unsigned when using the client in an AWS deployment.
> Fix unsiged S3 configuration when using in deployment

- .github/workflows/testing.yml
- src/mp_api/client.py
- src/mp_api/core/client.py
- src/mp_api/core/utils.py
- src/mp_api/routes/charge_density.py
- src/mp_api/routes/grain_boundary.py
- src/mp_api/routes/materials.py
- src/mp_api/routes/summary.py
- src/mp_api/routes/thermo.py
- src/mp_api/routes/xas.py
This PR adds formatting checks to all `material_id` and `task_id` values used in both single document  and general search queries.
> Add client side checks on material and task IDs

- requirements.txt
- setup.py
- src/mp_api/routes/molecules.py
- tests/test_mprester.py
Fixes the document model import in the `MoleculesRester`
> Update molecules doc import

- src/mp_api/routes/xas.py
- tests/test_xas.py
Fixes issues with `edge` and `spectrum_type` not getting formatted correctly in the GET request when using the generic `search` method in the XASRester.
> Fix edge and spectrum type in xas client

- src/mp_api/core/settings.py
Fixes issues with `exclude_elements` queries not returning correct results due to incorrect requests parallelization.
> Add exclude elements to list of non-parallel

- src/mp_api/core/client.py
Disable `requests.Session.trust_env` on default to use HTTP_PROXY/HTTPS_PROXY env and avoid unexpected behavior.
Please let me know if any specific reason exists to need `requests.Session.trust_env=true` on default.
see: [requests.Session.trust_env](https://requests.readthedocs.io/en/latest/api/?highlight=trust_env#requests.Session.trust_env)
We have an application running behind a HTTP proxy using HTTP_PROXY and HTTPS_PROXY env because of security purpose. We tried to use mp-api, then we observed the client use the proxy for `contribs-api.materialsproject.org` endpoint, but doesn't use the proxy for `api.materialsproject.org`. After the investigation, we found `requests.Session.trus_env=false` ignore the environment variables of proxy servers.
-  [x] disable `requests.Session.trus_env` …
> disable requests.Session.trus_env on default

- src/mp_api/core/client.py
This PR introduces post-processing on returned document models to:
- Remove unset attributes and add them to new `fields_not_requested` attribute
- Add custom `__repr__` and `__str__` methods
- Add custom attribute error for unset but available data
> Enhance output objects

- requirements.txt
- setup.py
This fixes de-serialization issues with certain data in `TaskDoc` objects.
> Add custodian as a dependency

- src/mp_api/core/client.py
Raise `AttributerError` for `MPDataDoc` objects instead of `MPResterError` to ensure `hasattr` is functional.
> Raise attribute error for `MPDataDoc`

- mp_api/client/core/client.py
This PR fixes speed issues caused by repeated running of `MPDataDoc` factory for each returned document in a chunk.
> Only run `MPDataDoc` factory once per chunk

- mp_api/client/client.py
- mp_api/client/core/client.py
- mp_api/client/core/utils.py
- mp_api/client/routes/__init__.py
- mp_api/client/routes/alloys.py
- requirements.txt
- setup.py
- `custodian`, `mpcontribs-client`, `boto3`, and `emmet-core[all]` made optional dependencies
- `AlloyRester` import altered with warning to handle when `pymatgen-analysis-alloys` is not installed via `emmet-core`
> Clean up dependencies

- setup.py
`msgpack` added to reqs for BS, DOS, and CHGCAR data retrieval.
> Add msgpack to reqs

- .pre-commit-config.yaml
- mp_api/client/routes/electrodes.py
- mp_api/client/routes/electronic_structure.py
- mp_api/client/routes/materials.py
- mp_api/client/routes/summary.py
- mp_api/client/routes/thermo.py
- setup.cfg
This query currently errors
```
from pymatgen.ext.matproj import MPRester
MPRester().summary.search(
num_elements=1, fields=["material_id", "pretty_formula", "energy_per_atom"]
)
```
with
```py
TypeError: 'int' object is not subscriptable
```
since it should be `num_elements=[1, 1]` instead of `num_elements=1`.
The error message isn't very clear so one improvement might be to ask the user to pass a tuple instead. This PR instead converts the value to a tuple on the fly when detecting `int`:
```py
if isinstance(num_elements, int):
num_elements = (num_elements, num_elements)
```
In the case of summary.search, it converts all values to tuple when detecting `int` or `float`.
```py
for param, value in locals().items():
if param in min_max_name_dict and value:
if isinstance(value, (int, …
```
> Support single values instead of (min, max) tuples as summary search filters

- .github/workflows/release.yml
- .github/workflows/testing.yml
- tests/test_thermo.py
Bump `actions/setup-python@v4` and `actions/checkout@v3`.
> Use latest GH actions

- .github/workflows/testing.yml
This PR adds multiple API keys to the testing workflow to avoid rate limit issues from the six parallel runs.
> Use six API keys in testing workflow instead of one

- mp_api/client/mprester.py
- tests/test_mprester.py
This PR ensures backwards compatibility between the legacy MPRester top level methods involving getting `ComputedStructureEntry` objects. Specifically,
- MPRester.get_entries
- MPRester.get_entries_in_chemsys
- MPRester.get_entry_by_material_id
For most of the added arguments, the missing functionality is fully implemented. The two that are deprecated are `additional_criteria` and `inc_structure`. The user is warned when passing these directly. Additional warnings are included in the docstrings.
> Ensure parity with top level legacy methods

- .github/workflows/testing.yml
- .gitignore
- mp_api/client/core/settings.py
- mp_api/client/mprester.py
- tests/test_client.py
- tests/test_mprester.py
- tests/test_tasks.py
`additional_criteria` in top level entry related methods now passes arguments to `MPRester.thermo.search`
> Add back `additional_criteria` as an input to `get_entries` and `get_entries_in_chemsys`

- .github/workflows/testing.yml
- mp_api/client/core/client.py
- mp_api/client/core/settings.py
- tests/test_mprester.py
This PR implements smarter parallel chunking of request URLs that takes into account a max character number for HTTP URLs.
A new settings parameter is used to define the max character number which defaults to 2000.
> Smart chunk with max URL length consideration

- setup.py
There is a missing comma on line 36 of `setup.py` that causes `"emmet-core[all]>=0.36.4"` and `"custodian"` to be interpreted as one string.
This then corrupts the `poetry.lock` that gets generated for projects that depend on `mp-api`, e.g.
```toml
[[package]]
name = "mp-api"
version = "0.29.2"
description = "API Server for the Materials Project"
category = "main"
optional = false
python-versions = ">=3.8"
[package.dependencies]
emmet-core = ">=0.36.4"
monty = ">=2021.3.12"
msgpack = "*"
pymatgen = ">=2022.3.7"
requests = ">=2.23.0"
typing-extensions = ">=3.7.4.1"
[package.extras]
all = ["boto3", "emmet-core[all] (>=0.36.4custodian)", "mpcontribs-client"]
```
yields
```
[...]
Installing dependencies from lock file
Could not parse version constraint: >=0.36.4custodian
```
> Insert missing comma in setup.py

- mp_api/client/routes/charge_density.py
- tests/test_charge_density.py
Fixes a bug where `task_id` list queries were not getting formatted properly for the charge density related methods.
> Fix charge density `task_ids` list query

- mp_api/client/core/settings.py
The order should be (User setting in python) > (environment variables) > (pmgrc.yaml settings)
> Allow the pmgrc file to be read for the MPREster settings

- mp_api/client/routes/robocrys.py
Ensure `num_chunks` and `chunk_size` work properly with robocrys search method.
> Fix robocrys search pagination

- mp_api/client/core/client.py
- mp_api/client/mprester.py
- Header dict pass through added to `MPRester` and `BaseRester`.
- `BaseRester` not imports `MaterialsRester` for document ID checks instead of `MPRester`.
> Header dictionary pass through and `BaseRester` nesting fix

- mp_api/client/core/client.py
- mp_api/client/mprester.py
- Ability added to pass an already instantiated `Session` object to `MPRester`
- Custom headers are now passed to each request
> Custom sessions

- mp_api/client/mprester.py
- mp_api/client/routes/thermo.py
- requirements.txt
- setup.py
- tests/test_elasticity.py
- tests/test_mprester.py
- tests/test_tasks.py
- tests/test_thermo.py
Ensure `ThermoType.GGA_GGA_U` is the default return type for all thermo data accessed through `MPRester.thermo.search`.
> Set default thermo_type in thermo search method

- mp_api/client/routes/thermo.py
Ensure keys for `el_refs` attribute of `PhaseDiagram` objects are returned as `Element` objects instead of strings. This ensures `PDPlotter` can be called on them. This is will fixed in pymatgen shortly.
> Fix `el_refs` dict keys in `PhaseDiagram` objects

- mp_api/client/mprester.py
- mp_api/client/routes/thermo.py
Let me know if I should add a test for this.
Also, I just used `str` in the type hint as using `Literal` would break single source of truth for accepted values. But happy to change that if you prefer `Literal`.
> Accept `list[str]` for `thermo_types` in `ThermoRester.search()`

- mp_api/client/mprester.py
Quick fix that addresses #735.
Converts the list of user-provided elements to a set so that duplicates are removed.
> Add duplicate element checking in `MPRester.get_entries_in_chemsys`

- mp_api/client/core/client.py
- mp_api/client/core/settings.py
This will introduce a delay between successive API calls if retries are required. A setting was added to make this optional/user-controllable.
> Small edit to add `backoff_factor` to client

- mp_api/client/mprester.py
- tests/test_mprester.py
- tests/test_thermo.py
This PR disables monty decoding for nested objects in `tasks` and `provenance` to fix issues related to varying schema. Objects with types defined in the pydantic models are still instantiated for these endpoints.
> Disable nested monty decode for some data

- mp_api/client/core/client.py
This PR overloads the `dict` method of the `MPDataDoc` pydantic model to use `emmet.core.utils.jsanitize`. This fixes dumping the documents directly with monty for docs with non-standard key types.
> Overload model dict to fix monty dumping

- mp_api/client/core/client.py
@munrojm this PR configures `boto3.resource` to send unsigned requests. I tested this to make sure that users don't need an AWS account or credentials in order to access our OpenData buckets. If you could make another release candidate, I could test this in production. Thanks!
> unsigned boto3

- mp_api/client/routes/_user_settings.py
Replaced the user setting post method with the patch method. 
The reason for the change is that now we have a `settings.message_last_read` nested field that couldn't be changed manually by the user, and it would make sense to only partially update some fields in the settings.
> replace method post with patch for user setting  

- mp_api/client/mprester.py
- mp_api/client/routes/_user_settings.py
- mp_api/client/routes/materials/molecules.py
All materials related resters are now nested under `MPRester.materials`. For example, `MPRester.materials.summary`. These resters can still be accessed as a top level attribute of `MPRester`, but a deprecation warning is presented to the user. Additionally, all molecule related resters are nested under `MPRester.molecules`, including the legacy rester under `MPRester.molecules.jcesr`.
> Nest all resters

- mp_api/client/mprester.py
Clarifies the top level `get_entries` method to avoid confusion with what looks like multiple entries for a single `material_id`. Relevant issue: https://github.com/materialsproject/api/issues/841
> Clarify top level get_entries method

- mp_api/client/routes/_user_settings.py
Added terms agreement field to the patch method for user settings.  
This will need to go out along with the front-end changes for checking our latest terms. 
By clicking the box on our website, it will patch an additional data field to our consumer store.
> patch agreed_terms field for user settings

- mp_api/client/core/client.py
This PR converts pydantic deserialization calls to use `dict(model)` instead of `model.model_dump()` to avoid some edge cases with root level instantiated python objects being partially de-serialized.
Note this is not an issue in pydantic v1.
> Fix pydantic deserialization issues with root obj

- .pre-commit-config.yaml
- mp_api/client/mprester.py
- mp_api/client/routes/materials/substrates.py
- tests/test_mprester.py
Brings behavior more in line with legacy rester in `pymatgen.ext.matproj` which looks for API key in `~/.config/.pmgrc.yaml` if not passed explicitly.
> Read API key from `pymatgen` config

- mp_api/client/mprester.py
- mp_api/client/routes/materials/elasticity.py
- tests/test_mprester.py
Ensure the MPContribs client is dynamically instantiated in the `MPRester`
> Dynamically instantiate MPContribs client

- pyproject.toml
@munrojm just making sure the latest `emmet-core` release candidate is used. Would you mind re-releasing `mp-api`? Thanks!
> use latest emmet-core rc

- mp_api/client/core/client.py
- mp_api/client/mprester.py
It looks like ruff was a bit too rough with this docstring in https://github.com/materialsproject/api/pull/772, which messes up the rendered API docs for this class (see `__init__` and class docstring at https://materialsproject.github.io/api/_autosummary/mp_api.client.mprester.MPRester.html). This PR fixes it by adding a throwaway line at the top and then follows the appropriate docstring format (feel free to edit the content itself), I also added entries for `s3_resource` and `mute_progress_bars` as best I could.
I haven't tried building the docs locally but 99% sure this will work.
> Fix rendering of MPRester docstring in deployed docs

- mp_api/client/routes/molecules/jcesr.py
- tests/molecules/test_jcesr.py
Adds a query on `task_ids` to the legacy molecules rester
> Add task_ids query to legacy molecules rester

- mp_api/client/routes/materials/robocrys.py
Fixes generic robocrys document queries by removing deprecated query argument.
> Remove deprecated arg from robocrys search

- mp_api/client/routes/materials/summary.py
fix for https://matsci.org/t/issue-with-search-mp-api-with-has-props/57147/2 @computron
> allow strings for has_props

- mp_api/client/mprester.py
- tests/test_mprester.py
Fixes #924
Major changes:
- Added `MPRester.get_charge_density_from_task_id()` to obtain charge densities from task id
Note that the `test_get_charge_density_from_material_id()` is currently failing, and was failing independently of this PR. This is due to an issue in emmet from [task.search](https://github.com/materialsproject/api/blob/main/mp_api/client/mprester.py#L1334):
```
def model_post_init(self, __context: Any) -> None:
>       for inp_set in [self.calcs_reversed[0].input, self.input, self.orig_inputs]:
E       TypeError: 'NoneType' object is not subscriptable
venv/lib/python3.10/site-packages/emmet/core/tasks.py:453: TypeError
```
Should be reproducible with:
```
python -m pytest tests/test_mprester.py -k test_get_charge_density_data
```
on `main` branch. 
I can submit a …
> Add MPRester.get_charge_density_from_task_id()

- .github/workflows/testing.yml
- mp_api/client/core/client.py
- mp_api/client/mprester.py
- tests/materials/test_materials.py
- tests/materials/test_summary.py
- tests/materials/test_tasks.py
- tests/materials/test_thermo.py
- tests/materials/test_xas.py
- tests/molecules/test_jcesr.py
- tests/molecules/test_summary.py
- tests/test_client.py
- tests/test_mprester.py
- Lazily get `endpoint` and `api_key`, to close #935
> `MPRester` lazily get `endpoint` and `api_key`  

- requirements/requirements-ubuntu-latest_py3.10.txt
- requirements/requirements-ubuntu-latest_py3.10_extras.txt
- requirements/requirements-ubuntu-latest_py3.11.txt
- requirements/requirements-ubuntu-latest_py3.11_extras.txt
Full log: https://github.com/materialsproject/api/actions/runs/11169960273 (THIS IS AN AUTOMATED COMMENT)
> Automated dependency upgrades

- mp_api/client/core/client.py
- requirements/requirements-ubuntu-latest_py3.10.txt
- requirements/requirements-ubuntu-latest_py3.10_extras.txt
- requirements/requirements-ubuntu-latest_py3.11.txt
- requirements/requirements-ubuntu-latest_py3.11_extras.txt
> `model_fields` not settable directly

- mp_api/client/mprester.py
- tests/test_mprester.py
Adds in [legacy API feature](https://github.com/materialsproject/pymatgen/blob/da607e86f9ce8aec942067c6c1a4fda6e04915dd/src/pymatgen/ext/matproj_legacy.py#L1271) to compute cohesive energies on the fly from tabulated reference atomic energies. Pulls in atomic data that is hosted on [MPContribs](https://next-gen.materialsproject.org/contribs/projects/isolated_atom_energies) and cached
This feature has been requested by [users on matsci](https://matsci.org/t/get-cohesive-energy-from-materials-project/58195)
The legacy API normalized the cohesive energy by formula unit - this is less common than normalizing by atom. By atom normalization is now the default. with an option to instead normalize by formula unit.
To-do's:
~- Add SCAN atom calculations (in progress calculating)~
~- Add tests~
~- …
> Add cohesive energy support

- mp_api/client/mprester.py
- mp_api/client/routes/materials/thermo.py
- tests/test_client.py
- tests/test_mprester.py
see **https://matsci.org/t/inquiry-regarding-discrepancy-in-phase-diagram-data-from-api-and-web-interface/60035/2**
> retrieve prebuild phase diagrams from OpenData

- mp_api/client/core/settings.py
Fix the deprecation 
```
pydantic.warnings.PydanticDeprecatedSince20: Support for 
class-based `config` is deprecated, use ConfigDict instead. 
Deprecated in Pydantic V2.0 to be removed in V3.0. 
See Pydantic V2 Migration Guide at 
https://errors.pydantic.dev/2.10/migration/
```
> Fix source of `PydanticDeprecatedSince20` warning

- mp_api/client/mprester.py
- tests/test_mprester.py
> run tests for `get_stability`

- mp_api/client/mprester.py
- mp_api/client/routes/materials/phonon.py
Small tweak to `MPRester.get_pourbaix_entries` to allow for the user to specify a list of `ComputedEntry` / `ComputedStructureEntry` objects for placement on the Pourbaix diagram
> Feature: allow for user to add entries to Pourbaix

- tests/materials/test_robocrys.py
Robocrys search prior to [emmet PR 1261](https://github.com/materialsproject/emmet/pull/1261) fails when the result set of the query is large. 
This adds a test that is skipped for now. It needs to be enabled once the emmet API with that change is deployed.
> add test for large result set on robocrys search

- pyproject.toml
Dear Maintainers,
We are slowly trying to remove the legacy runtime of `setuptools` from Debian
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1083669
This is not obvious if you don't know Debian's `dh-python` build system
that translate the `setuptools` dependency into the `python3-pk-resources` runtime.
.... this is not even obvious to most Debian contributors 😅
> setuptools is not needed at runtime
