- requirements-server.txt
- requirements.txt
- setup.py
- src/mp_api/core/api.py
This PR updates package version numbers to fix the docker build step.
> Package version updates. 

- requirements.txt
- setup.py
PR to fix pymatgen version requirement.
> Pymatgen version update

- requirements.txt
- setup.py
Another pymatgen version update to fix build step.
> Another pymatgen update

- src/mp_api/core/api.py
PR to make docs and redoc protected with api keys.
> Docs protected with api key

- src/mp_api/bandstructure/client.py
- src/mp_api/core/api.py
- src/mp_api/core/client.py
- src/mp_api/dos/client.py
- src/mp_api/eos/client.py
- src/mp_api/matproj.py
- src/mp_api/similarity/client.py
- src/mp_api/tasks/client.py
- src/mp_api/xas/client.py
Included in this PR is:
- RESTer client enhancements
- Base64 decoding added to api keys
- Improved error handling
> Base64 decode PR

- src/mp_api/materials/client.py
- src/mp_api/materials/models/doc.py
- src/mp_api/materials/resources.py
This PR adds a structure matching endpoint and method to the existing materials endpoint and client rester.
> Find structure endpoint added

- app.py
- src/mp_api/core/query_operator.py
- src/mp_api/core/resource.py
- src/mp_api/fermi/client.py
- src/mp_api/fermi/models.py
- src/mp_api/fermi/resources.py
- src/mp_api/materials/resources.py
- src/mp_api/materials/utils.py
- src/mp_api/tasks/resources.py
This PR contains the following:
- Fermi surface endpoint added
- Always make search endpoints validate query params
> Fermi surface endpoint, search endpoint query param validation

- src/mp_api/core/query_operator.py
- src/mp_api/fermi/client.py
- Search method added to fermi rester
- Model name fixed for text describing `fields` query parameter
> Fermi rester and field text update

- app.py
- src/mp_api/dois/client.py
- src/mp_api/dois/models.py
- src/mp_api/dois/resources.py
- src/mp_api/eos/client.py
- src/mp_api/gb/client.py
- src/mp_api/materials/client.py
- src/mp_api/materials/query_operators.py
- src/mp_api/materials/resources.py
- src/mp_api/substrates/client.py
- src/mp_api/substrates/models.py
- src/mp_api/substrates/query_operators.py
- src/mp_api/substrates/resources.py
- src/mp_api/surface_properties/client.py
- src/mp_api/surface_properties/models.py
- src/mp_api/surface_properties/query_operators.py
- src/mp_api/surface_properties/resources.py
- src/mp_api/wulff/client.py
- src/mp_api/wulff/models.py
- src/mp_api/wulff/resources.py
- DOI endpoint added
- Substrates endpoint added
- Find structure endpoint rename
- Find structure data now sorted and optional limit added
- Surface properties endpoint added
- Wulff endpoint added
> Large endpoint update

- src/mp_api/materials/resources.py
Fix bug with find structure not taking into consideration limit variable
> Find structure limit bug fix

- app.py
- src/mp_api/core/client.py
- src/mp_api/core/resource.py
- src/mp_api/materials/client.py
- src/mp_api/matproj.py
- src/mp_api/tasks/models.py
- src/mp_api/thermo/client.py
- src/mp_api/thermo/models.py
- src/mp_api/thermo/query_operators.py
- src/mp_api/thermo/resources.py
- Fields added to task endpoint
- Thermo endpoint added
- General `query_by_task_id` method added to client
> Thermo endpoint and tasks update

- app.py
- src/mp_api/elasticity/client.py
- src/mp_api/elasticity/models.py
- src/mp_api/elasticity/query_operators.py
- src/mp_api/elasticity/resources.py
- src/mp_api/tasks/resources.py
- Task deprecation endpoint added
- Elasticity endpoint added
> Elasticity and task deprecation endpoint

- app.py
- src/mp_api/dielectric/client.py
- src/mp_api/dielectric/models.py
- src/mp_api/dielectric/query_operators.py
- src/mp_api/dielectric/resources.py
- src/mp_api/phonon/client.py
- src/mp_api/phonon/models.py
- src/mp_api/phonon/resources.py
- src/mp_api/piezo/client.py
- src/mp_api/piezo/models.py
- src/mp_api/piezo/query_operators.py
- src/mp_api/piezo/resources.py
- src/mp_api/wulff/models.py
- Piezoelectric endpoint added
- Dielectric endpoint added
- Phonon band structure endpoint added
- Phonon image endpoint added
> Piezo, Dielectric, Phonon endpoints

- app.py
- src/mp_api/search/models.py
- src/mp_api/search/query_operators.py
- src/mp_api/search/resources.py
- src/mp_api/thermo/models.py
> Search endpoint added

- app.py
- src/mp_api/magnetism/client.py
- src/mp_api/magnetism/models.py
- src/mp_api/magnetism/query_operators.py
- src/mp_api/magnetism/resources.py
This PR includes:
- Magnetism endpoint added
> Magnetism endpoint

- src/mp_api/phonon/resources.py
This PR contains the follow:
- Phonon image endpoint altered to only return raw image data
> Update to phonon image endpoint

- src/mp_api/phonon/resources.py
Updated phonon image endpoint error handling.
> Phonon img endpoint error handling

- app.py
- src/mp_api/core/client.py
- src/mp_api/magnetism/client.py
- src/mp_api/robocrys/client.py
- src/mp_api/robocrys/resources.py
- src/mp_api/search/query_operators.py
- src/mp_api/search/resources.py
- src/mp_api/synth/client.py
- src/mp_api/synth/client.pyi
- src/mp_api/synth/models.py
- src/mp_api/synth/resources.py
- src/mp_api/thermo/query_operators.py
- Thermo endpoint and search endpoint bug fixes with `is_stable` field
- Synthesis text search endpoint added
- Robocrys text search endpoint renamed
> Synthesis text search endpoint, is_stable bug fix, robocrys text search rename

- src/mp_api/core/resource.py
This PR fixes a bug with versioned store collection names and MongoClient connections.
> Versioned query bug fix

- src/mp_api/electrodes/models.py
Added model for electrode documents
> [WIP] Electrode endpoint

- app.py
- src/mp_api/molecules/client.py
- src/mp_api/molecules/models.py
- src/mp_api/molecules/query_operators.py
- src/mp_api/molecules/resources.py
- src/mp_api/xas/client.py
- src/mp_api/xas/query_operator.py
- src/mp_api/xas/resources.py
- Molecules endpoint added 
- XAS search endpoint now allows a list of `task_ids` to be passed
> Molecules endpoint, XAS task_ids search

- app.py
- src/mp_api/bandstructure/resources.py
- src/mp_api/charge_density/models.py
- src/mp_api/charge_density/resources.py
- src/mp_api/molecules/client.py
- src/mp_api/molecules/models.py
- src/mp_api/molecules/query_operators.py
- src/mp_api/xas/client.py
- src/mp_api/xas/query_operator.py
- src/mp_api/xas/resources.py
- Initial draft charge density endpoint added
- Molecules endpoint IP to IE
> Charge density endpoint, molecules IP to IE

- src/mp_api/electrodes/models.py
- src/mp_api/electrodes/query_operators.py
Added insertion electrode endpoint.
Requires Change to `pymatgen.core.periodic_table` to function properly.
Done here https://github.com/materialsproject/pymatgen/pull/2005
> Working Electrode endpoint

- src/mp_api/electrodes/models.py
- src/mp_api/electrodes/query_operators.py
Reverts materialsproject/api#159
Need to way for pymatgen to update.
> Revert "Working Electrode endpoint"

- app.py
- src/mp_api/electrodes/models.py
- src/mp_api/electrodes/query_operators.py
- src/mp_api/matproj.py
- src/mp_api/molecules/client.py
- src/mp_api/molecules/models.py
- src/mp_api/molecules/query_operators.py
- src/mp_api/molecules/resources.py
- src/mp_api/synth/client.py
- src/mp_api/synthesis/client.py
- src/mp_api/synthesis/client.pyi
- src/mp_api/synthesis/models.py
- src/mp_api/synthesis/query_operators.py
- src/mp_api/synthesis/resources.py
- Formula and task_id list searching added to molecules endpoint
- Formula searching added to synthesis endpoint
> Molecule and synthesis search update

- src/mp_api/elasticity/models.py
- src/mp_api/materials/query_operators.py
- src/mp_api/search/models.py
- src/mp_api/search/query_operators.py
- src/mp_api/search/resources.py
- Elasticity model bug fix for voigt entries
- Elasticity search query op fix
- Magnetism query operator added to search endpoint
- Piezo and dielectric query op added to search endpoint
- Ability to query on excluded elements added to material and search endpoints
> Elasticity bug fix, search endpoint additions, excluded elements query op

- app.py
- src/mp_api/magnetism/models.py
- src/mp_api/magnetism/query_operators.py
- src/mp_api/materials/resources.py
- src/mp_api/search/query_operators.py
- Removed total magnetization enum as a query option
- Improved formula search endpoint
> Improved autocomplete, removed magnetism normalization enum

- src/mp_api/core/resource.py
> MAPISettings added to base resource class

- app.py
- requirements-server.txt
- requirements.txt
- src/mp_api/core/client.py
This PR sets the appropriate version of maggma and ES store keys
> Maggma version bump fix and ES key change

- .github/workflows/testing.yml
This PR enables auto-release on push to main
> Enable auto release on push to main

- .github/workflows/release.yaml
- README.md
Enable auto pypi publishing on release.
> Enable auto pypi publish on release

- app.py
- requirements.txt
- src/mp_api/matproj.py
- src/mp_api/routes/oxidation_states/resources.py
- src/mp_api/routes/robocrys/client.py
- src/mp_api/routes/robocrys/models.py
- src/mp_api/routes/summary/client.py
- src/mp_api/routes/summary/resources.py
- src/mp_api/routes/thermo/client.py
- tests/electronic_structure/test_client.py
- tests/robocrys/test_client.py
- tests/test_client.py
- tests/test_mprester.py
- tests/thermo/test_client.py
Small updates include:
- Oxi states data can now be queried via summary
- Equilibrium reaction energy typo fixes
> Small oxidation state and thermo changes

- app.py
- src/mp_api/client.py
- src/mp_api/routes/elasticity/query_operators.py
- src/mp_api/routes/elasticity/resources.py
- src/mp_api/routes/electrodes/client.py
- src/mp_api/routes/electronic_structure/client.py
- src/mp_api/routes/electronic_structure/resources.py
- src/mp_api/routes/materials/client.py
- src/mp_api/routes/materials/query_operators.py
- src/mp_api/routes/materials/resources.py
- src/mp_api/routes/materials/utils.py
- src/mp_api/routes/oxidation_states/resources.py
- src/mp_api/routes/summary/client.py
- src/mp_api/routes/summary/resources.py
- src/mp_api/routes/tasks/client.py
- src/mp_api/routes/tasks/resources.py
- src/mp_api/routes/thermo/client.py
- src/mp_api/routes/thermo/resources.py
- src/mp_api/routes/xas/client.py
- src/mp_api/routes/xas/resources.py
- tests/elasticity/test_query_operators.py
- tests/electrodes/test_client.py
- tests/electronic_structure/test_client.py
- tests/materials/test_client.py
- tests/materials/test_query_operators.py
- tests/materials/test_utils.py
- tests/tasks/test_client.py
- tests/test_mprester.py
- tests/thermo/test_client.py
- tests/xas/test_client.py
This PR splits `chemsys` and `formula` into two separate query parameters for all endpoints.
> Split formula chemsys 

- requirements.txt
- setup.py
- src/mp_api/routes/molecules.py
Fix molecules import to go along with module rename in emmet
> Fix molecules import

- requirements.txt
- setup.py
- src/mp_api/routes/alloys.py
- tests/test_client.py
Bumps maggma to use changes in https://github.com/materialsproject/maggma/pull/690
> Bump maggma to fix pydantic model sanitization

- src/mp_api/core/client.py
Adds a default timeout value of 20 seconds to get requests made with the client.
> Add timeout to get requests in core client

- mp_api/client/routes/thermo.py
Ensures `qhull_data` passed as part of `computed_data` to `PhaseDiagram` is a numpy array.
> Ensure PhaseDiagram qhull_data is a numpy array

- mp_api/client/mprester.py
- mp_api/client/routes/__init__.py
- mp_api/client/routes/chemenv.py
Add `ChemenvRester` to query for chemical environment data.
> Chemenv rester

- mp_api/client/mprester.py
Fixes an issue where the legacy molecules rester suffix was not properly getting mapped to the correct attribute of `MPRester`.
> Fix MPRester attr mapping

- requirements/requirements-macos-latest_py3.10.txt
- requirements/requirements-macos-latest_py3.10_extras.txt
- requirements/requirements-macos-latest_py3.8.txt
- requirements/requirements-macos-latest_py3.8_extras.txt
- requirements/requirements-macos-latest_py3.9.txt
- requirements/requirements-macos-latest_py3.9_extras.txt
- requirements/requirements-ubuntu-latest_py3.10.txt
- requirements/requirements-ubuntu-latest_py3.10_extras.txt
- requirements/requirements-ubuntu-latest_py3.8.txt
- requirements/requirements-ubuntu-latest_py3.8_extras.txt
- requirements/requirements-ubuntu-latest_py3.9.txt
- requirements/requirements-ubuntu-latest_py3.9_extras.txt
- requirements/requirements-windows-latest_py3.10.txt
- requirements/requirements-windows-latest_py3.10_extras.txt
- requirements/requirements-windows-latest_py3.8.txt
- requirements/requirements-windows-latest_py3.8_extras.txt
- requirements/requirements-windows-latest_py3.9.txt
- requirements/requirements-windows-latest_py3.9_extras.txt
Full log: https://github.com/materialsproject/api/actions/runs/5271524557 (THIS IS AN AUTOMATED COMMENT)
> Automated dependency upgrades

- mp_api/client/mprester.py
Adds a check for Cloudflare errors early in client instantiation to better handle communicating to temporarily banned users.
> Accommodate cloudflare errors

- mp_api/client/core/client.py
- mp_api/client/mprester.py
Arg added to `MPRester` to mute progress bars.
> Add arg to mute progress bars

- mp_api/client/core/client.py
- tests/molecules/test_summary.py
Ensure the user agent information contains the mp-api version and not pymatgen.
> Switch user-agent to mp-api version

- mp_api/client/core/client.py
only check root-level of requested field for validity
> nested fields are not invalid

- mp_api/client/core/settings.py
Reverts materialsproject/api#967
> Revert "Fix source of `PydanticDeprecatedSince20` warning"
